package fireblazer

import (
	"context"
	"fmt"
	"net/http"
	"sync"
	"time"

	"golang.org/x/sync/errgroup"
)

var p4saProducts = []string{
	"accessapproval",
	"adsdatahub",
	"agentgateway",
	"aiplatform",
	"aiplatform-cc",
	"aiplatform-ft",
	"aiplatform-is",
	"aiplatform-pie",
	"aiplatform-re",
	"aiplatform-vm",
	"alloydb",
	"anthos",
	"anthosaudit",
	"anthosconfigmanagement",
	"anthosidentityservice",
	"anthosmulticloud",
	"anthospolicycontroller",
	"anthossupport",
	"apigateway",
	"apigateway-mgmt",
	"apigee",
	"apigeeregistry",
	"apihub",
	"apikeys",
	"apim",
	"appdevexperience",
	"appengine",
	"apphub",
	"appoptimize",
	"artifactregistry",
	"asm-hpsa",
	"assuredoss",
	"assuredworkloads",
	"audit-manager",
	"autoannotate",
	"automl",
	"backupdr",
	"backupdr-pr",
	"backupdr-run",
	"baremetalsolution",
	"batch",
	"beyondcorp",
	"biglake",
	"biglakerestcatalog",
	"bigquery-condel",
	"bigquery-consp",
	"bigqueryconnection",
	"bigquerydatapolicy",
	"bigquerydatatransfer",
	"bigquerymigration",
	"bigqueryreservation",
	"bigqueryri",
	"bigqueryspark",
	"bigquerytardis",
	"bigtable",
	"bigtableadmin",
	"binaryauthorization",
	"bms",
	"bne",
	"bqms",
	"bundles",
	"ccai-cmek",
	"ccaip",
	"ccinsights-cmek",
	"certificateauthority",
	"certificatemanager",
	"ces",
	"chromepolicy",
	"chronicle",
	"chronicle-org",
	"chronicle-soar",
	"cloud-cw",
	"cloud-cw-cmek",
	"cloud-ekg",
	"cloud-sql",
	"cloud-trace",
	"cloudaicompanion",
	"cloudasset",
	"cloudbatch",
	"cloudbuild",
	"cloudcontrolspartner",
	"clouddebugger",
	"clouddeploy",
	"cloudfunctions",
	"cloudiot",
	"cloudkms",
	"cloudoptim",
	"cloudprofiler",
	"cloudresourcemanager",
	"cloudscheduler",
	"cloudsearch",
	"cloudsupport",
	"cloudtasks",
	"cloudtrace",
	"composer",
	"compute",
	"compute-usage",
	"config",
	"configdelivery",
	"connectedsheets",
	"connectors",
	"contactcenterinsights",
	"containeranalysis",
	"containerregistry",
	"containerscanning",
	"containersec",
	"crashlytics",
	"csc-hpsa",
	"datacatalog",
	"dataconnectors",
	"dataflow",
	"dataform",
	"datafusion",
	"datalabeling",
	"datamigration",
	"datapipelines",
	"dataplex",
	"dataplex-cmek",
	"dataproc",
	"dataprocrmnode",
	"datastore",
	"datastream",
	"datastudio",
	"datastudio-cmek",
	"dep",
	"deploymentmanager",
	"designcenter",
	"devconnect",
	"dialogflow",
	"dialogflow-cmek",
	"discoveryengine",
	"dlp",
	"dns",
	"documentai",
	"domains",
	"edgecontainer",
	"edgecontainercluster",
	"edgecontainergcr",
	"effectivepolicy",
	"ekms",
	"endpoints",
	"essentialcontacts",
	"eventarc",
	"file",
	"firebase",
	"firebaseappcheck",
	"firebaseapphosting",
	"firebasedatabase",
	"firebasedataconnect",
	"firebasehosting",
	"firebaseml",
	"firebasemods",
	"firebaseremoteconfig",
	"firebasestorage",
	"firebasevertexai",
	"firestore",
	"firewallinsights",
	"fs-spanner",
	"gameservices",
	"geminicodeassistmp",
	"geminidataanalytics",
	"generativelanguage",
	"genomics",
	"gkebackup",
	"gkeconnect",
	"gkedataplanev2",
	"gkehub",
	"gkemulticloud",
	"gkemulticloudcontainer",
	"gkemulticloudcpmachine",
	"gkemulticloudnpmachine",
	"gkenode",
	"gkeonprem",
	"global-spanner",
	"gsuiteaddons",
	"healthcare",
	"hypercomputecluster",
	"iam",
	"iap",
	"iap-corp",
	"identitytoolkit",
	"ids",
	"integrations",
	"ivs",
	"krmapihosting",
	"krmapihosting-dataplane",
	"ktd-control",
	"ktd-hpsa",
	"lifesciences",
	"livestream",
	"logging",
	"looker",
	"lustre",
	"managedflink",
	"managedidentities",
	"managedkafka",
	"mcmetering",
	"mcsd",
	"memcache",
	"memorystore",
	"meshconfig",
	"meshcontrolplane",
	"meshdataplane",
	"metastore",
	"mi",
	"migcenter",
	"ml",
	"modelarmor",
	"monitoring",
	"monitoring-notification",
	"multiclusteringress",
	"netapp",
	"networkactions",
	"networkconnectivity",
	"networkmanagement",
	"networksecurity",
	"networkservices",
	"notebooks",
	"notebooks-vm",
	"notebooksecurityscanner",
	"ns-authz",
	"nss-hpsa",
	"observability",
	"oci",
	"ondemandscanning",
	"osconfig",
	"osconfig-rollout",
	"oslogin",
	"othercloudcfg",
	"pam",
	"parallelstore",
	"playbooks",
	"pm",
	"policytroubleshooter",
	"privateca",
	"prod-bigqueryomni",
	"prod-dai-core",
	"progrollout",
	"pubsub",
	"pubsublite",
	"rbe",
	"recaptchaenterprise",
	"recommendationengine",
	"redis",
	"remotebuild",
	"retail",
	"riskmanager",
	"rma",
	"routeoptim",
	"run",
	"run-ai",
	"runapps",
	"saasservicemgmt",
	"scc-bulk-export",
	"scc-notification",
	"scc-vmtd",
	"sccspanner",
	"secretmanager",
	"securewebproxy",
	"securitycenter",
	"serviceconsumermanagement",
	"servicedirectory",
	"servicemanagement",
	"servicemesh",
	"serviceusage",
	"sourcemanager",
	"sourcerepo",
	"spanner",
	"spectrumsas",
	"speech",
	"sqladmin",
	"storage",
	"storage-search",
	"storageinsights",
	"storagetransfer",
	"stream",
	"tpu",
	"transcoder",
	"transferappliance",
	"translate",
	"translation",
	"v1-remediator",
	"vectorsearch",
	"vertex-agent",
	"vertex-bp",
	"vertex-es",
	"vertex-eval",
	"vertex-ex",
	"vertex-ex-cc",
	"vertex-logging",
	"vertex-mm",
	"vertex-moss-ft",
	"vertex-nb",
	"vertex-op",
	"vertex-rag",
	"vertex-sandbox",
	"vertex-shtune",
	"vertex-skills",
	"vertex-telemetry",
	"vertex-tune",
	"vertex-vtc",
	"visionai",
	"vmmigration",
	"vmwareengine",
	"vpcaccess",
	"vs-cmek",
	"webrisk",
	"websecurityscanner",
	"workflows",
	"workloadmanager",
	"workstations",
	"workstationsvm",
}

func EnumerateServiceAccounts(projectNum string, workerCount int) ([]string, error) {
	var mu sync.Mutex
	var foundProducts []string

	g, ctx := errgroup.WithContext(context.Background())
	g.SetLimit(workerCount)

	for _, product := range p4saProducts {
		product := product // do NOT question my sanity
		g.Go(func() error {
			email := fmt.Sprintf("service-%s@gcp-sa-%s.iam.gserviceaccount.com", projectNum, product)
			url := fmt.Sprintf("https://iam.googleapis.com/v1/projects/%s/serviceAccounts/%s", projectNum, email)

			for retries := 0; retries < 3; retries++ {
				select {
				case <-ctx.Done():
					return ctx.Err()
				default:
				}

				req, err := http.NewRequest("GET", url, nil)
				if err != nil {
					return nil
				}

				// this is actually an unauthed project thing LMAO you could use this for any project ID with no key at all
				resp, err := ReqHeaderOnly(*req, "", false)
				if err != nil {
					return nil
				}

				statusCode := resp.StatusCode
				resp.Body.Close()

				if statusCode == 200 || statusCode == 403 {
					mu.Lock()
					foundProducts = append(foundProducts, product)
					mu.Unlock()
					return nil
				} else if statusCode == 502 || statusCode == 503 || statusCode == 429 {
					time.Sleep(2 * time.Second) // a 429 should NEVER happen. I mean, NEVER. It's an unauthed resource. Still, I've dealt with too many edgecases with Drive, and want to ensure nothing like that happens again.
					continue                    // never thought i'd need a retry...
				} else {
					return nil
				}
			}
			return nil
		})
	}

	if err := g.Wait(); err != nil {
		return nil, err
	}

	return foundProducts, nil
}
